name: Continuous Integration

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SALESFORCE_USERNAME: ${{ secrets.PLAYGROUND_USERNAME }}
      SALESFORCE_PASSWORD: ${{ secrets.PLAYGROUND_PASSWORD }}
      SALESFORCE_INSTANCE_URL: "https://wise-impala-axjif7-dev-ed.trailblaze.my.salesforce.com/"

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Server key PRE
      run: echo "$GITHUB_CONTEXT"

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core

    - name: Server key
      run: echo "ASDA" > server1.key

    - name: Authenticate to Salesforce
      run: |
          echo "${{ secrets.SFDC_KEY }}" > server.key
    
    - name: Deploy
      run: | 
          echo "hola"
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY }} --jwtkeyfile server.key --username $SALESFORCE_USERNAME --setalias devhub
          node_modules/sfdx-cli/bin/run force:org:display --json -u $SALESFORCE_USERNAME > sfdx-auth.json
          node_modules/sfdx-cli/bin/run force:source:deploy -x ./manifest/package.xml -l RunLocalTests -u devhub 
